const country = 'Bangladesh';
const age =21.5;
const isIndepedent= true;
const Student ={id: 121,class:11,Name: 'Agun'};
const friend = [13,14,11,17,21,16,15,20];
console.log(typeof country);
console.log(typeof age);
console.log(typeof isIndepedent);
console.log(typeof Student);
console.log(Array.isArray( friend));
console.log(country.includes('B'));